### PR TITLE
Deprecate `master` branch in favor of `main`

### LINKED ISSUE #1: Create and move to "main" branch
This can be done in the settings tab.

### PR DESCRIPTION
**Pull request by Mr0grog**
This adds a deprecation notice to the README on the `master` branch and is part of edgi-govdata-archiving/overview#243. Once this is approved, I’m happy to also add the `main` branch and change the default branch settings if nobody else is able to.

@shansen5 I’m not highly involved in this repo, so won’t make any changes without sign-off here from you.

### CODE REVIEW

**Comment by ericnost** [comment]
@Mr0grog I think this can be merged. Will do.

**Comment by Mr0grog** [comment]
Add a branch protection rule for `master`, too. :)

**Comment by ericnost** [comment]
Ah of course - thanks for catching that @Mr0grog! (and for doing it on other repos it looks like?)

**Comment by Mr0grog** [comment]
Yep, did it on them all.

**Pull request merged**
